sudo: false
language: python
python:
    - "3.6"
install:
    - pip install python-coveralls
    - pip install -r requirements.txt
script:
    - cp AuthKey.cfg.sample AuthKey.cfg
    - sed -i -e 's/API_KEY = 9908......................c2cf7/API_KEY = '"$GH_token"'/g' AuthKey.cfg
    - flake8 --exclude=venv,setup.py --max-line-length=90
    - pytest
